module.exports =
[
    [],
    
    [
        {"relTeamName":"A","teamCode":"MRVAC","numF0Records":"","sexCode":"X","eventDist":"200","strokeCode":"7","eventNum":"1","eventAgeCode":"UN12","totalAge":"0","swimDate":"01282017","seedTime":"2:14.37","courseCode1":"Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"2:12.14","courseCode4":"Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"4","prelimPlace":"","finalsPlace":"2","pointsScored":"6.","eventTimeClass":"","swimmers":[{"teamCode":"MRVAC","teamName":"A","swimmerName":"Dickman, Rian","ussNum":"051404RIAKDI","citizenCode":"USA","birthdate":"05142004","swimmerAge":"12","sexCode":"F","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"1","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"051404RIAKDICK","prefFirstName":""},{"teamCode":"MRVAC","teamName":"A","swimmerName":"Storaska, Nathaniel W","ussNum":"071604NATWST","citizenCode":"USA","birthdate":"07162004","swimmerAge":"12","sexCode":"M","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"2","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"071604NATWSTOR","prefFirstName":""},{"teamCode":"MRVAC","teamName":"A","swimmerName":"Dickman, Kellen","ussNum":"051404KEL*DI","citizenCode":"USA","birthdate":"05142004","swimmerAge":"12","sexCode":"M","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"3","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"051404KEL*DICK","prefFirstName":""},{"teamCode":"MRVAC","teamName":"A","swimmerName":"Wienckowski, Grace A","ussNum":"060304GRAAWI","citizenCode":"USA","birthdate":"06032004","swimmerAge":"12","sexCode":"F","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"4","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"060304GRAAWIEN","prefFirstName":""}]},
        
        {"relTeamName":"A","teamCode":"MRWSSC","numF0Records":"","sexCode":"X","eventDist":"200","strokeCode":"7","eventNum":"1","eventAgeCode":"UN12","totalAge":"0","swimDate":"01282017","seedTime":"2:06.04","courseCode1":"Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"2:00.40","courseCode4":"Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"3","prelimPlace":"","finalsPlace":"1","pointsScored":"10.","eventTimeClass":"","swimmers":[{"teamCode":"MRWSSC","teamName":"A","swimmerName":"Wright, Hannah E","ussNum":"092004HANEWR","citizenCode":"USA","birthdate":"09202004","swimmerAge":"12","sexCode":"F","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"1","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"092004HANEWRIG","prefFirstName":"Hannah"},{"teamCode":"MRWSSC","teamName":"A","swimmerName":"Kellman, Adam H","ussNum":"061104ADAHKE","citizenCode":"USA","birthdate":"06112004","swimmerAge":"12","sexCode":"M","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"2","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"061104ADAHKELL","prefFirstName":"Adam"},{"teamCode":"MRWSSC","teamName":"A","swimmerName":"Meffert, Jack W","ussNum":"061504JACWME","citizenCode":"USA","birthdate":"06152004","swimmerAge":"12","sexCode":"M","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"3","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"061504JACWMEFF","prefFirstName":"Jack"},{"teamCode":"MRWSSC","teamName":"A","swimmerName":"DiLiberto, Samantha F","ussNum":"030304SAMFDI","citizenCode":"USA","birthdate":"03032004","swimmerAge":"12","sexCode":"F","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"4","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"030304SAMFDILI","prefFirstName":"Samantha"}]}
    ],
    
    [
        {"relTeamName":"A","teamCode":"MRVAC","numF0Records":"","sexCode":"X","eventDist":"200","strokeCode":"7","eventNum":"2","eventAgeCode":"13OV","totalAge":"0","swimDate":"01282017","seedTime":"2:03.59","courseCode1":"Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:58.86","courseCode4":"Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"2","finalsLaneNum":"2","prelimPlace":"","finalsPlace":"1","pointsScored":"10.","eventTimeClass":"","swimmers":[{"teamCode":"MRVAC","teamName":"A","swimmerName":"Sanchez, Ryan O","ussNum":"083102RYAOSA","citizenCode":"USA","birthdate":"08312002","swimmerAge":"14","sexCode":"M","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"1","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"083102RYAOSANC","prefFirstName":""},{"teamCode":"MRVAC","teamName":"A","swimmerName":"Zock, Joshua L","ussNum":"020799JOSLZO","citizenCode":"USA","birthdate":"02071999","swimmerAge":"17","sexCode":"M","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"2","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"020799JOSLZOCK","prefFirstName":""},{"teamCode":"MRVAC","teamName":"A","swimmerName":"Satriano, Delia","ussNum":"073102DEL*SA","citizenCode":"USA","birthdate":"07312002","swimmerAge":"14","sexCode":"F","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"3","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"073102DEL*SATR","prefFirstName":""},{"teamCode":"MRVAC","teamName":"A","swimmerName":"Garcia, Naihomy T","ussNum":"032802NAITGA","citizenCode":"USA","birthdate":"03282002","swimmerAge":"14","sexCode":"F","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"4","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"032802NAITGARC","prefFirstName":""}]},
        
        {"relTeamName":"A","teamCode":"MRWSSC","numF0Records":"","sexCode":"X","eventDist":"200","strokeCode":"7","eventNum":"2","eventAgeCode":"13OV","totalAge":"0","swimDate":"01282017","seedTime":"1:52.24","courseCode1":"Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"2:02.53","courseCode4":"Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"2","finalsLaneNum":"3","prelimPlace":"","finalsPlace":"2","pointsScored":"6.","eventTimeClass":"","swimmers":[{"teamCode":"MRWSSC","teamName":"A","swimmerName":"Miller, Elissa J","ussNum":"081302ELIJMI","citizenCode":"USA","birthdate":"08132002","swimmerAge":"14","sexCode":"F","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"1","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"081302ELIJMILL","prefFirstName":"Elissa"},{"teamCode":"MRWSSC","teamName":"A","swimmerName":"Donlon, Jillian P","ussNum":"031499JILPDO","citizenCode":"USA","birthdate":"03141999","swimmerAge":"17","sexCode":"F","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"2","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"031499JILPDONL","prefFirstName":""},{"teamCode":"MRWSSC","teamName":"A","swimmerName":"Vojta, Thomas","ussNum":"101900THOJVO","citizenCode":"USA","birthdate":"10192000","swimmerAge":"16","sexCode":"M","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"3","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"101900THOJVOJT","prefFirstName":"Thomas"},{"teamCode":"MRWSSC","teamName":"A","swimmerName":"Neporanny, Nicholas P","ussNum":"103099NICPNE","citizenCode":"USA","birthdate":"10301999","swimmerAge":"17","sexCode":"M","prelimOrderCode":"","swimoffOrderCode":"","finalsOrderCode":"4","legTime":"","courseCode":"","takeoffTime":"","ussNumNew":"103099NICPNEPO","prefFirstName":"Nicholas"}]}
    ],
    
    [
        {"swimmerName":"Geiselhart, Kori R","ussNum":"020607KORRGE","attachCode":"A","citizenCode":"USA","birthDate":"02062007","swimmerAge":"9","sexCode":"F","eventSex":"F","eventDist":"100","strokeCode":"5","eventNum":"3","eventAgeCode":"UN10","dateOfSwim":"01282017","seedTime":"","courseCode":"17","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"NSY","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"1","prelimPlace":"","finalsPlace":"0","pointsScored":"","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Geiselhart, Kori R","ussNum":"020607KORRGE","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"","splitTime2":"","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]},
        
        {"swimmerName":"Barton, Presley K","ussNum":"120506PREKBA","attachCode":"A","citizenCode":"USA","birthDate":"12052006","swimmerAge":"9","sexCode":"F","eventSex":"F","eventDist":"100","strokeCode":"5","eventNum":"3","eventAgeCode":"UN10","dateOfSwim":"01282017","seedTime":"1:34.05","courseCode":"17 1:34.05Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:40.88Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"2","prelimPlace":"","finalsPlace":"3","pointsScored":"","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Barton, Presley K","ussNum":"120506PREKBA","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"46.51","splitTime2":"1:40.88","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]},
        
        {"swimmerName":"Cunnane, Lara M","ussNum":"123106LARMCU","attachCode":"A","citizenCode":"USA","birthDate":"12312006","swimmerAge":"9","sexCode":"F","eventSex":"F","eventDist":"100","strokeCode":"5","eventNum":"3","eventAgeCode":"UN10","dateOfSwim":"01282017","seedTime":"1:27.74","courseCode":"17 1:27.74Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:27.90Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"3","prelimPlace":"","finalsPlace":"1","pointsScored":"5.","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Cunnane, Lara M","ussNum":"123106LARMCU","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"39.57","splitTime2":"1:27.90","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]},
        
        {"swimmerName":"Fischer, Paige","ussNum":"041206PAI*FI","attachCode":"A","citizenCode":"USA","birthDate":"04122006","swimmerAge":"10","sexCode":"F","eventSex":"F","eventDist":"100","strokeCode":"5","eventNum":"3","eventAgeCode":"UN10","dateOfSwim":"01282017","seedTime":"1:30.00","courseCode":"17 1:30.00Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:28.58Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"4","prelimPlace":"","finalsPlace":"2","pointsScored":"3.","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Fischer, Paige","ussNum":"041206PAI*FI","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"39.40","splitTime2":"1:28.58","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]}
    ],
    
    [
        {"swimmerName":"Elkashef, Adam T","ussNum":"030906ADATEL","attachCode":"A","citizenCode":"USA","birthDate":"03092006","swimmerAge":"10","sexCode":"M","eventSex":"M","eventDist":"100","strokeCode":"5","eventNum":"4","eventAgeCode":"UN10","dateOfSwim":"01282017","seedTime":"1:46.70","courseCode":"17 1:46.70Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:43.99Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"2","prelimPlace":"","finalsPlace":"3","pointsScored":"1.","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Elkashef, Adam T","ussNum":"030906ADATEL","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"46.70","splitTime2":"1:43.99","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]},
        
        {"swimmerName":"Bertocchi, Thomas J","ussNum":"051006THOJBE","attachCode":"A","citizenCode":"USA","birthDate":"05102006","swimmerAge":"10","sexCode":"M","eventSex":"M","eventDist":"100","strokeCode":"5","eventNum":"4","eventAgeCode":"UN10","dateOfSwim":"01282017","seedTime":"1:35.61","courseCode":"17 1:35.61Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:31.51Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"3","prelimPlace":"","finalsPlace":"1","pointsScored":"5.","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Bertocchi, Thomas J","ussNum":"051006THOJBE","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"42.85","splitTime2":"1:31.51","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"},{"swimmerName":"Bertocchi, Thomas J","ussNum":"051006THOJBE","sequenceNum":"1","totalSplits":"4","splitDistance":"50","splitCode":"C","splitTime1":"1:11.73","splitTime2":"","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]},
        
        {"swimmerName":"Roa, Raymond","ussNum":"042606RAY*RO","attachCode":"A","citizenCode":"USA","birthDate":"04262006","swimmerAge":"10","sexCode":"M","eventSex":"M","eventDist":"100","strokeCode":"5","eventNum":"4","eventAgeCode":"UN10","dateOfSwim":"01282017","seedTime":"1:40.22","courseCode":"17 1:40.22Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:32.67Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"4","prelimPlace":"","finalsPlace":"2","pointsScored":"3.","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Roa, Raymond","ussNum":"042606RAY*RO","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"43.34","splitTime2":"1:32.67","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]}
    ],
    
    [
        {"swimmerName":"Restivo, Giannie S","ussNum":"050405GIASRE","attachCode":"A","citizenCode":"USA","birthDate":"05042005","swimmerAge":"11","sexCode":"F","eventSex":"F","eventDist":"100","strokeCode":"5","eventNum":"5","eventAgeCode":"UN12","dateOfSwim":"01282017","seedTime":"","courseCode":"17","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:36.51Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"2","prelimPlace":"","finalsPlace":"7","pointsScored":"","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Restivo, Giannie S","ussNum":"050405GIASRE","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"43.56","splitTime2":"1:36.51","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]},
        
        {"swimmerName":"White, Cali E","ussNum":"121004CALEWH","attachCode":"A","citizenCode":"USA","birthDate":"12102004","swimmerAge":"11","sexCode":"F","eventSex":"F","eventDist":"100","strokeCode":"5","eventNum":"5","eventAgeCode":"UN12","dateOfSwim":"01282017","seedTime":"","courseCode":"17","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:29.82Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"4","prelimPlace":"","finalsPlace":"5","pointsScored":"","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"White, Cali E","ussNum":"121004CALEWH","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"42.40","splitTime2":"1:29.82","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"},{"swimmerName":"White, Cali E","ussNum":"121004CALEWH","sequenceNum":"1","totalSplits":"4","splitDistance":"50","splitCode":"C","splitTime1":"2:33.41","splitTime2":"","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"},{"swimmerName":"White, Cali E","ussNum":"121004CALEWH","sequenceNum":"1","totalSplits":"4","splitDistance":"50","splitCode":"C","splitTime1":"1:11.40","splitTime2":"","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]},
        
        {"swimmerName":"Wienckowski, Grace A","ussNum":"060304GRAAWI","attachCode":"A","citizenCode":"USA","birthDate":"06032004","swimmerAge":"12","sexCode":"F","eventSex":"F","eventDist":"100","strokeCode":"5","eventNum":"5","eventAgeCode":"UN12","dateOfSwim":"01282017","seedTime":"1:12.00","courseCode":"17 1:12.00Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:10.82Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"2","finalsLaneNum":"4","prelimPlace":"","finalsPlace":"1","pointsScored":"5.","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Wienckowski, Grace A","ussNum":"060304GRAAWI","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"32.96","splitTime2":"1:10.82","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"},{"swimmerName":"Wienckowski, Grace A","ussNum":"060304GRAAWI","sequenceNum":"1","totalSplits":"4","splitDistance":"50","splitCode":"C","splitTime1":"2:12.14","splitTime2":"","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"},{"swimmerName":"Wienckowski, Grace A","ussNum":"060304GRAAWI","sequenceNum":"1","totalSplits":"4","splitDistance":"50","splitCode":"C","splitTime1":"2:12.10","splitTime2":"","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]},
        
        {"swimmerName":"Brown, Madison G","ussNum":"061305MADGBR","attachCode":"A","citizenCode":"USA","birthDate":"06132005","swimmerAge":"11","sexCode":"F","eventSex":"F","eventDist":"100","strokeCode":"5","eventNum":"5","eventAgeCode":"UN12","dateOfSwim":"01282017","seedTime":"1:33.03","courseCode":"17 1:33.03Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:28.44Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"2","finalsLaneNum":"1","prelimPlace":"","finalsPlace":"4","pointsScored":"","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Brown, Madison G","ussNum":"061305MADGBR","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"42.20","splitTime2":"1:28.44","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]},
        
        {"swimmerName":"DiLiberto, Samantha F","ussNum":"030304SAMFDI","attachCode":"A","citizenCode":"USA","birthDate":"03032004","swimmerAge":"12","sexCode":"F","eventSex":"F","eventDist":"100","strokeCode":"5","eventNum":"5","eventAgeCode":"UN12","dateOfSwim":"01282017","seedTime":"1:11.54","courseCode":"17 1:11.54Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:11.66Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"2","finalsLaneNum":"3","prelimPlace":"","finalsPlace":"2","pointsScored":"3.","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"DiLiberto, Samantha F","ussNum":"030304SAMFDI","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"34.50","splitTime2":"1:11.66","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"},
        
        {"swimmerName":"DiLiberto, Samantha F","ussNum":"030304SAMFDI","sequenceNum":"1","totalSplits":"4","splitDistance":"50","splitCode":"C","splitTime1":"2:00.40","splitTime2":"","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"},{"swimmerName":"DiLiberto, Samantha F","ussNum":"030304SAMFDI","sequenceNum":"1","totalSplits":"4","splitDistance":"50","splitCode":"C","splitTime1":"1:56.24","splitTime2":"","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]},
        
        {"swimmerName":"Sullivan, Hannah R","ussNum":"040505HANRSU","attachCode":"A","citizenCode":"USA","birthDate":"04052005","swimmerAge":"11","sexCode":"F","eventSex":"F","eventDist":"100","strokeCode":"5","eventNum":"5","eventAgeCode":"UN12","dateOfSwim":"01282017","seedTime":"1:34.32","courseCode":"17 1:34.32Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:31.65Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"2","finalsLaneNum":"6","prelimPlace":"","finalsPlace":"6","pointsScored":"","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Sullivan, Hannah R","ussNum":"040505HANRSU","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"42.95","splitTime2":"1:31.65","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]},
        
        {"swimmerName":"Wright, Hannah E","ussNum":"092004HANEWR","attachCode":"A","citizenCode":"USA","birthDate":"09202004","swimmerAge":"12","sexCode":"F","eventSex":"F","eventDist":"100","strokeCode":"5","eventNum":"5","eventAgeCode":"UN12","dateOfSwim":"01282017","seedTime":"1:15.36","courseCode":"17 1:15.36Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:16.79Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"2","finalsLaneNum":"2","prelimPlace":"","finalsPlace":"3","pointsScored":"1.","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Wright, Hannah E","ussNum":"092004HANEWR","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"35.37","splitTime2":"1:16.79","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]}
    ],
    
    [
        {"swimmerName":"Grabinski, Thomas","ussNum":"122304THO*GR","attachCode":"A","citizenCode":"USA","birthDate":"12232004","swimmerAge":"11","sexCode":"M","eventSex":"M","eventDist":"100","strokeCode":"5","eventNum":"6","eventAgeCode":"UN12","dateOfSwim":"01282017","seedTime":"","courseCode":"17","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:31.78Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"1","prelimPlace":"","finalsPlace":"2","pointsScored":"3.","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Grabinski, Thomas","ussNum":"122304THO*GR","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"6.12","splitTime2":"1:31.78","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"},{"swimmerName":"Grabinski, Thomas","ussNum":"122304THO*GR","sequenceNum":"1","totalSplits":"4","splitDistance":"50","splitCode":"C","splitTime1":"41.04","splitTime2":"","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"},{"swimmerName":"Grabinski, Thomas","ussNum":"122304THO*GR","sequenceNum":"1","totalSplits":"4","splitDistance":"50","splitCode":"C","splitTime1":"1:02.39","splitTime2":"","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]},
        
        {"swimmerName":"Grabinski, Timothy J","ussNum":"122304TIMJGR","attachCode":"A","citizenCode":"USA","birthDate":"12232004","swimmerAge":"11","sexCode":"M","eventSex":"M","eventDist":"100","strokeCode":"5","eventNum":"6","eventAgeCode":"UN12","dateOfSwim":"01282017","seedTime":"","courseCode":"17","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"DQY","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"5","prelimPlace":"","finalsPlace":"0","pointsScored":"","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Grabinski, Timothy J","ussNum":"122304TIMJGR","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"42.01","splitTime2":"1:33.43","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"},{"swimmerName":"Grabinski, Timothy J","ussNum":"122304TIMJGR","sequenceNum":"1","totalSplits":"4","splitDistance":"50","splitCode":"C","splitTime1":"2:18.56","splitTime2":"","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]},
        
        {"swimmerName":"Nasser, Gabriel D","ussNum":"052504GABDNA","attachCode":"A","citizenCode":"USA","birthDate":"05252004","swimmerAge":"12","sexCode":"M","eventSex":"M","eventDist":"100","strokeCode":"5","eventNum":"6","eventAgeCode":"UN12","dateOfSwim":"01282017","seedTime":"1:30.69","courseCode":"17 1:30.69Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:32.24Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"4","prelimPlace":"","finalsPlace":"3","pointsScored":"1.","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Nasser, Gabriel D","ussNum":"052504GABDNA","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"45.56","splitTime2":"1:32.24","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"},{"swimmerName":"Nasser, Gabriel D","ussNum":"052504GABDNA","sequenceNum":"1","totalSplits":"4","splitDistance":"50","splitCode":"C","splitTime1":"1:44.25","splitTime2":"","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]},
        
        {"swimmerName":"Sherman, Colin E","ussNum":"072104COLESH","attachCode":"A","citizenCode":"USA","birthDate":"07212004","swimmerAge":"12","sexCode":"M","eventSex":"M","eventDist":"100","strokeCode":"5","eventNum":"6","eventAgeCode":"UN12","dateOfSwim":"01282017","seedTime":"1:19.12","courseCode":"17 1:19.12Y","prelimTime":"","courseCode2":"","swimoffTime":"","courseCode3":"","finalsTime":"1:17.44Y","prelimHeatNum":"","prelimLaneNum":"","finalsHeatNum":"1","finalsLaneNum":"3","prelimPlace":"","finalsPlace":"1","pointsScored":"5.","eventTimeClass":"","flightStatus":"","splits":[{"swimmerName":"Sherman, Colin E","ussNum":"072104COLESH","sequenceNum":"1","totalSplits":"2","splitDistance":"50","splitCode":"C","splitTime1":"5.71","splitTime2":"1:17.44","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"},{"swimmerName":"Sherman, Colin E","ussNum":"072104COLESH","sequenceNum":"1","totalSplits":"4","splitDistance":"50","splitCode":"C","splitTime1":"1:48.53","splitTime2":"","splitTime3":"","splitTime4":"","splitTime5":"","splitTime6":"","splitTime7":"","splitTime8":"","splitTime9":"","splitTime10":"","prelimFinalCode":"F"}]}
    ]
];